name: events
run-name: Events

on:
#    - push
#    - pull_request
#- issues
  pull_request: 
    branches:
      #- "feature/**"
      - "main"
    paths:
      - ".js"
    

jobs:
    show-ref-and-sha:
        runs-on: ubuntu-latest
        steps:
            - name: Eho guithub_SHA and guithub_ref
              run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
